export enum OutboundStatus {
  READY_AT_FACTORY = 'READY_AT_FACTORY',
  SENT_TO_YANGON_GATE = 'SENT_TO_YANGON_GATE',
  IN_TRANSIT = 'IN_TRANSIT',
  AT_DESTINATION_GATE = 'AT_DESTINATION_GATE',
  RECEIVED_BY_CUSTOMER = 'RECEIVED_BY_CUSTOMER',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
}
